print -S "http :8080/stuffies/count"
print -S "http :8080/stuffies/for/alex"
print -S "http :8080/stuffies/for/sophie"
print -S "http :8080/stuffies/for/adam"
print -S "http :8080/stuffies/in/uk"
print -S "http :8080/stuffies/by/aurora"
print -S "http :8080/stuffies/by/jellycat"
print -S "http :8080/stuffie/3/for"
print -S "http :8080/stuffie/3/details"
print -S "http :8080/stuffie/3/pic | viu -"
print -S "http :8080/actuator/health"
print -S "./target/isdb-count-0.0.1-SNAPSHOT.jar"
print -S "http :8080/stuffie/0/pic | viu -"
print -S "docker compose down --volumes && docker compose up"
print -S "PGPASSWORD=isdb psql -U isdb -h localhost -p \$\(docker compose port postgres 5432 | cut -d: -f2\)"
print -S "unzip -l ./target/isdb-count-0.0.1-SNAPSHOT.jar | grep autocon"
print -S "unzip -l ./target/isdb-count-0.0.1-SNAPSHOT.jar | grep spring-boot"
print -S "http :8080/stuffie/0/for"
print -S "http :8080/stuffie/0/for 'API-Version: 2.0'"
