server:
  port: 8081

spring:
  application:
    name: isdb-web
  docker:
    compose:
      lifecycle-management: start-only
  http:
    clients:
      read-timeout: 1s
    serviceclient:
      stuffie:
        base-url: 'http://localhost:8080'
        apiversion:
          insert:
            header: API-Version

management:
  tracing:
    sampling:
      probability: 1.0
