server:
  port: 8081

spring:
  application:
    name: isdb-web
  docker:
    compose:
      lifecycle-management: start-only
  http:
    client:
      service:
        apiversion:
          insert:
            header: API-Version
        group:
          stuffie:
            base-url: 'http://localhost:8080'
            read-timeout: 1s
management:
  tracing:
    sampling:
      probability: 1.0
