spring:
  application:
    name: isdb
  flyway:
    baseline-on-migrate: true
  docker:
    compose:
      lifecycle-management: start-only
      skip:
        in-tests: false
  mvc:
    apiversion:
      default: '1.0'
      use:
        header: API-Version

management:
  endpoint:
    health:
      show-components: always
      show-details: always
